allCards = ['Royal Giant', 'Minions', 'Ram Rider', 'Royal Hogs', 'Rascals', 'Archer Queen', 'Royal Recruits', 'Goblins', 'Golem', 'Three Musketeers', 'Archers', 'X-Bow', 'Mother Witch', 'Spear Goblins', 'Barbarians', 'Skeleton Dragons', 'Lava Hound', 'Wall Breakers', 'Goblin Drill', 'Prince', 'Mortar', 'Bomber', 'Barbarian Hut', 'Hunter', 'Dart Goblin', 'Guards', 'Mini P.E.K.K.A', 'Furnace', 'Goblin Hut', 'Witch', 'Mega Minion', 'Skeleton Army', 'Giant', 'Goblin Cage', 'Ice Wizard', 'Dark Prince', 'Heal Spirit', 'Skeleton Barrel', 'Poison', 'Ice Spirit', 'Arrows', 'Goblin Gang', 'Giant Skeleton', 'Flying Machine', 'Clone', 'Fisherman', 'Zappies', 'Night Witch', 'Battle Ram', 'Fire Spirit', 'Mighty Miner', 'Inferno Tower', 'Earthquake', 'Princess', 'Electro Giant', 'Lightning', 'Skeleton King', 'Executioner', 'Electro Spirit', 'Cannon Cart', 'Tombstone', 'Wizard', 'Sparky', 'Goblin Barrel', 'Battle Healer', 'Valkyrie', 'Golden Knight', 'Bats', 'Elite Barbarians', 'Elixir Golem', 'Knight', 'Hog Rider', 'Mega Knight', 'Elixir Collector', 'Cannon', 'Minion Horde', 'Goblin Giant', 'Tesla', 'The Log', 'Mirror', 'Graveyard', 'Baby Dragon', 'Royal Delivery', 'Bowler', 'P.E.K.K.A', 'Magic Archer', 'Fireball', 'Zap', 'Royal Ghost', 'Bandit', 'Phoenix', 'Electro Wizard', 'Firecracker', 'Rocket', 'Freeze', 'Electro Dragon', 'Lumberjack', 'Inferno Dragon', 'Rage', 'Tornado', 'Musketeer', 'Bomb Tower', 'Barbarian Barrel', 'Miner', 'Ice Golem', 'Giant Snowball', 'Balloon', 'Skeletons', 'Monk']

win_conditions = ['Royal Giant', 'Ram Rider', 'Royal Hogs', 'Three Musketeers', 'Golem', 'Lava Hound', 'Wall Breakers', 'Goblin Drill', 'Prince', 'Giant', 'Skeleton Barrel', 'Night Witch', 'Mighty Miner', 'Electro Giant', 'Skeleton King', 'Sparky', 'Elite Barbarians', 'Hog Rider', 'Mega Knight', 'Elixir Golem', 'Royal Delivery', 'P.E.K.K.A', 'Balloon', 'Graveyard']

spells = ['Mother Witch', 'Poison', 'Arrows', 'Clone', 'Lightning', 'Rocket', 'Freeze', 'Fireball', 'Zap']

air_hitting = ['Minions', 'Spear Goblins', 'Skeleton Dragons', 'Mega Minion', 'Baby Dragon', 'Magic Archer', 'Firecracker', 'Electro Dragon', 'Inferno Dragon']

buildings = ['Barbarian Hut', 'Mortar', 'Inferno Tower', 'Cannon', 'Tombstone', 'Tesla', 'Bomb Tower']

support = ['Rascals', 'Archer Queen', 'Royal Recruits', 'Goblins', 'Archers', 'X-Bow', 'Dart Goblin', 'Guards', 'Mini P.E.K.K.A', 'Furnace', 'Goblin Hut', 'Witch', 'Skeleton Army', 'Goblin Cage', 'Ice Wizard', 'Dark Prince', 'Heal Spirit', 'Ice Spirit', 'Goblin Gang', 'Giant Skeleton', 'Flying Machine', 'Fisherman', 'Zappies', 'Battle Ram', 'Fire Spirit', 'Earthquake', 'Princess', 'Executioner', 'Electro Spirit', 'Cannon Cart', 'Wizard', 'Goblin Barrel', 'Battle Healer', 'Valkyrie', 'Golden Knight', 'Bats', 'Elixir Collector', 'Minion Horde', 'Goblin Giant', 'The Log', 'Mirror', 'Bowler', 'Bandit', 'Phoenix', 'Electro Wizard', 'Rage', 'Tornado', 'Musketeer', 'Barbarian Barrel', 'Miner', 'Ice Golem', 'Giant Snowball', 'Skeletons', 'Monk', 'Barbarians', 'Bomber', 'Hunter', 'Knight', 'Royal Ghost', 'Lumberjack']

copy = allCards

print(len(win_conditions) + len(spells) + len(air_hitting) + len(buildings) + len(support))